version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - CUSTOMER_SERVICE_URL=http://customer-service:3002
      - SALES_SERVICE_URL=http://sales-service:3003
    depends_on:
      user-service:
        condition: service_healthy
      customer-service:
        condition: service_healthy
      sales-service:
        condition: service_healthy
    networks:
      - crm-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://user-db:27017/user-db
      - JWT_SECRET=4f821b6d8237b1802a46670db6bc31c0cab881cf774d316f3c7e444d8a07420bf37c213864be4ae1098a83c20f248ea9992f9c899f64b01e0cf7d409fa78aae3
    depends_on:
      user-db:
        condition: service_started
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  customer-service:
    build: ./customer-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:password@customer-db:5432/customer-db
      - JWT_SECRET=4f821b6d8237b1802a46670db6bc31c0cab881cf774d316f3c7e444d8a07420bf37c213864be4ae1098a83c20f248ea9992f9c899f64b01e0cf7d409fa78aae3
    depends_on:
      customer-db:
        condition: service_healthy
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  sales-service:
    build: ./sales-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://sales-db:27017/sales-db
      - JWT_SECRET=4f821b6d8237b1802a46670db6bc31c0cab881cf774d316f3c7e444d8a07420bf37c213864be4ae1098a83c20f248ea9992f9c899f64b01e0cf7d409fa78aae3
    depends_on:
      sales-db:
        condition: service_started
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - user-db-data:/data/db
    networks:
      - crm-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3

  customer-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=customer-db
    volumes:
      - customer-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crm-network

  sales-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - sales-db-data:/data/db
    networks:
      - crm-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  user-db-data:
  customer-db-data:
  sales-db-data:

networks:
  crm-network:
    driver: bridge